function R = myrot(phi, theta, psi)

R = [cos(theta)*cos(psi)    -cos(phi)*sin(psi) + sin(phi)*sin(theta)*cos(psi)   sin(phi)*sin(psi) + cos(phi)*sin(theta)*cos(psi) 0; ...
     cos(theta)*sin(psi)    cos(phi)*cos(psi) + sin(phi)*sin(theta)*sin(psi)    -sin(phi)*cos(psi) + cos(phi)*sin(theta)*sin(psi) 0; ...
     -sin(theta)            sin(phi)*cos(theta)                                 cos(phi)*cos(theta) 0;...
     0 0 0 1];

end